### ISSUE TITLE
Oauth twitter and web printing

### ISSUE THREAD

**Issue by mazhead** [nordprojects/sirius#2]
Hello,
thank you for the https://littleprinter.nordprojects.co 
I was running a local fork of kpeeem modifications (https://github.com/mazhead/sirius) but twitter Oauth stopped working for me and currently I was unable to modify it to start working.

I see yours is still working but in this repo I do not see any modifications. Are you releasing your modifications or keeping them? 

In final my questions (hence the issue):

1. Are you able to release any modifications to this repo?
2. Would you consider adding modifications from kpeeem (picture web printing for example)?

**Comment by joerick** [comment]
Hey @mazhead!

1. The instance at https://littleprinter.nordprojects.co is auto-deployed from `master` here on Github, so we're not keeping any secret sauce back!

    (I do remember twitter logins breaking at one point, but I can't remember how I fixed it - I can't find any diffs either, maybe it was something in their console...?)

2. We have device keys and a client app to print pictures, although I'd be happy to look at a PR merging in some other enhancements from elsewhere in the ecosystem!

**Comment by banterability** [comment]
FWIW, I'm unable to log in with Twitter to the https://littleprinter.nordprojects.co instance. After authenticating with Twitter and redirecting back, it seems like the application isn't handling the request correctly:

<img width="520" alt="Screen Shot 2019-05-21 at 7 28 27 PM" src="https://user-images.githubusercontent.com/11073/58139099-e8d9ac80-7bfe-11e9-88b3-ab3dd6a30dcf.png">

I've tried a few different accounts and gone through the dance of revoking access on Twitter's end and retrying. Possible there's something that needs to be updated on the app side?

**Comment by joerick** [comment]
Hey @banterability ! Yes, we've just been dealing with a little scaling trouble after the press we got for this! That should be sorted now, fix is c6440df3428c7139c96871964ca791010a1944a1 if you're curious :)
