### ISSUE TITLE
Twitter authentication no longer working

### ISSUE THREAD

**Issue by phillipjf** [nordprojects/sirius#21]
Cannot login to https://littleprinter.nordprojects.co/ by clicking "Sign in with Twitter" Receiving `OAuth error from twitter!` message:

<img width="1178" alt="image" src="https://github.com/nordprojects/sirius/assets/8834707/d9b6fb5e-2b26-4b4c-818a-833adb832e06">

**Comment by joerick** [comment]
Ack, they binned our API key a couple of weeks back, I thought I had fixed it. 

Might just be a temporary error? Have you been seeing this for a while?

**Comment by phillipjf** [comment]
@joerick Probably about a week or so. First checked when I was walking through the install steps before I ordered a printer. In all the times I checked back, it's been giving the same error.

**Comment by joerick** [comment]
Just super. 
<img width="1162" alt="image" src="https://github.com/nordprojects/sirius/assets/1244307/f5addc52-b260-4c8c-a934-327a3c06a973">
I'll get in touch with them

**Comment by phillipjf** [comment]
It's not these values, right? If it is, possibly someone has grabbed them and is using them outside this app:
https://github.com/nordprojects/sirius/blob/master/sirius/web/twitter.py#L16-L17

**Comment by joerick** [comment]
No, it's not those values, we set different ones with env vars on the server. Not sure what those refer to!

**Comment by joerick** [comment]
The original version of sirius used a lot of Twitter API as part of its feature set. I think the way forward would be to strip all of that code out and redo the twitter sign in using modern Oauth. All we need is the user's twitter username to associate with our existing accounts. We'll probably have to stick with twitter as it's the only user identifier we have in our existing database (i.e. we dont have email addresses, so we can't switch to a different auth provider because there's no way to link that to an existing account)

A PR tackling the above would be welcome!

**Comment by phillipjf** [comment]
@joerick I think I've got something almost ready but when I was looking, the login flow fetches "friends" but it doesn't look like they're used anymore. Can this logic be dropped?

https://github.com/nordprojects/sirius/blob/master/sirius/web/twitter.py#L83-L113
https://github.com/nordprojects/sirius/blob/master/sirius/web/twitter.py#L68-L70

edit: looks like the required access for getting followers might be restricted to a paid plan now so I'm not able to test implementation anyways.

**Comment by joerick** [comment]
Brilliant! Yes, perhaps that's one of the API calls that got us on their naughty list. We don't need that.

**Comment by Neelfyn** [comment]
> All we need is the user's twitter username to associate with our existing accounts. We'll probably have to stick with twitter as it's the only user identifier we have in our existing database (i.e. we dont have email addresses, so we can't switch to a different auth provider because there's no way to link that to an existing account)

Just wanted to drop a line in case totally ditching Twitter is ever considered: logging into nord-sirius is literally the only reason I still have a Twitter account! 😄
