### ISSUE TITLE
Report of red flashing lights on bridges 🚨

### ISSUE THREAD

**Issue by notjosh** [nordprojects/sirius#9]
References: https://github.com/genmon/sirius/issues/26#issuecomment-538762234, https://github.com/genmon/sirius/issues/26#issuecomment-538844127, https://github.com/genmon/sirius/issues/26#issuecomment-539194809

For example:

> I flashed my bridge a couple months ago and it worked fine until recently. Now the red light is on and stays on. I unplugged the bridge and little printer multiple times, but it still doesn’t work. Has anyone had this problem and have a solution?

The timing seems to be "in the last couple of weeks" which would roughly align with #7 going live. So, I suspect something went wrong there.

Checking server logs, I'm seeing entries coming back from bridges like:

> `Oct 07 02:11:47.850pm debug app web.1 sirius.protocol.protocol_loop:Received BridgeLog(bridge_address='[redacted]', records=[{'name': 'bridge', 'created': 1570482710.281479, 'process': 465, 'levelno': 50, 'processName': 'MainProcess', 'message': "Unexpected command thread error: - <class 'struct.error'> : unpack requires a string argument of length 16", 'levelname': 'CRITICAL'}, {'name': 'bridge', 'created': 1570482710.303787, 'process': 465, 'levelno': 50, 'processName': 'MainProcess', 'message': ' in file PKGTMP.35950/usr/local/bergcloud-bridge/weminuche_bridge.py, line 391, function executeBridgeCommand - None', 'levelname': 'CRITICAL'}, {'name': 'bridge', 'created': 1570482710.306734, 'process': 465, 'levelno': 50, 'processName': 'MainProcess', 'message': ' in file PKGTMP.35950/usr/local/bergcloud-bridge/weminuche_bridge.py, line 336, function executeCommand - None', 'levelname': 'CRITICAL'}]).`

My _guess_ here is something about Python 3's `bytes` vs `str` and somehow a byte value like `0x01` is being sent as simply `"1"` instead of `"000...01"`, or something to that effect. So, depending the image you're trying to print, some aren't impacted? Which might explain why it's working fine for some folks?

If we can gather some specific bridge IDs of those impacted, we can try to verify the issue for individuals, and roll out a fix.

**Comment by jeremyfranklin** [comment]
My Little Printer says it is online, but I have the red light. Where do I find the ID?

**Comment by notjosh** [comment]
That's...actually a really good question. I don't think it's trivially accessible from your end. Maybe if we start with one of:

- printer ID (from the URL, like `https://littleprinter.nordprojects.co/printer/:id`)
- your claim URL (like `https://littleprinter.nordprojects.co/:id/:username/claim`)
- the claim code you used fro the printer

Any one of those should be enough to help track it down.

You're welcome to email it over, if you're not stoked on having those details floating around on GitHub too! (email in profile).

**Comment by jeremyfranklin** [comment]
Sent it your way.

**Comment by notjosh** [comment]
Welp, frustratingly, I added some tooling that seemed to work just fine!

I manually dumped the event payload, looks something like:

```json
{
  "type": "DeviceCommand",
  "bridge_address": "some-bridge-address",
  "command_id": 1,
  "timestamp": "0",
  "binary_payload": "[base64 blob]",
  "device_address": "[redacted]"
}
```

And it decoded in my sandbox as:

![iTerm2EJrVnp](https://user-images.githubusercontent.com/33126/66370907-9eab5a80-e956-11e9-9b3d-05449361cf12.png)

(images get sent upside down for printing, so this is correct).

SO, that means potentially one of a couple of things:

1. the failed encoding is in one of the values I stubbed out here, which seems unlikely?
1. I'm looking at the wrong thing. which seems more likely :)

**Comment by notjosh** [comment]
OKAY, yes, duh, I'm looking at the wrong thing. The error mentions `executeBridgeCommand`, and "unpack requires a string argument of length 16", so I'm guessing that's pointing us at [this line](https://github.com/nordprojects/berg-bridge-dump/blob/master/DECOMPILED/weminuche_bridge.pyc.py#L302), which makes way more sense.

I'll take another look tomorrow when I get a chance!

**Comment by notjosh** [comment]
Okay, took a quick look, and think I figured it out.

[`claiming.process_claim_code`](https://github.com/nordprojects/sirius/blob/master/sirius/coding/claiming.py#L140-L156) returns a base64'd string, and [`encoders.encode_bridge_command`](https://github.com/nordprojects/sirius/blob/master/sirius/coding/encoders.py#L99-L101) was incorrectly updated to wrap that value in base64. Yo dawg.

I'll add a test, fix it, and push a release tomorrow, then hopefully we should be seeing printers back online.

**Comment by notjosh** [comment]
Hiya @jeremyfranklin, I've merged/deployed a potential fix. Can you let me know if it gets your printer back in action?

**Comment by jeremyfranklin** [comment]
@notjosh I can let you know tonight.

**Comment by dickverbunt** [comment]
Mine is back alive! Awesome work @notjosh.

**Comment by jeremyfranklin** [comment]
@notjosh It works! Amazing work and thank you.
